---
javascripts:
- home:
  - jquery.min
  - application
- explore:
  - jquery.min
  - application
  - whs/features/index
- feature:
  - jquery.min
  - application
  - galleria-1.2.2
  - whs/features/show
