development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: whs_development
  username: postgres
  password:

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: whs_test
  username: postgres
  password:

staging:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: whs_staging
  username: postgres
  password:

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: whs_production
  username: postgres
  password:
